checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  tests:
    override:
      - pylint-run transitions
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
filter:
  excluded_paths:
    - tests/*
